#!/bin/bash

# Limit to as2-streaming-user
if [ "$HOME" != "/home/as2-streaming-user" ]; then
  echo "Home: $HOME"
  exit 1
fi


# Load dotfiles from the persistent storage
# Define the source and target directories
source_file="$HOME/MyFiles/HomeFolder/_configs/dotfiles.tar.gz"
target_dir="$HOME"

# Ensure the source directory exists
if [ ! -f "$source_file" ]; then
  echo "Source file does not exist: $source_file"
  exit 1
fi

# Change to the source directory
if [ ! -d "$target_dir" ]; then
  echo "Target directory does not exist: $target_dir"
  exit 1
fi

tar -xvf "$source_file" -C "$target_dir"

echo "Symbolic links created successfully!"

