#!/bin/bash

# Limit to as2-streaming-user
if [ ! "$HOME" = "/home/as2-streaming-user" ]; then
  echo "Home: $HOME"
  exit 1
fi

source_dir="$HOME"
target_dir="$HOME/MyFiles/HomeFolder/configs"

# Ensure source directory exists
if [ ! -d "$source_dir" ]; then
  echo "Source directory does not exist: $source_dir" >&2
  exit 1
fi

# Ensure target directory exists
if [ ! -d "$target_dir" ]; then
  echo "Target directory does not exist: $target_dir" >&2
  exit 1
else
  owner=$(stat -c '%U' "$target_dir")
  if [ "$owner" = "root" ]; then
    echo "The owner of the target directory is root: $target_dir"
    exit 1
  fi
fi

# Sync dotfiles and directories, excluding symbolic links
# Be careful to avoid self-reference loop
rsync -avP --no-links \
  --exclude='MyFiles' \
  --exclude='.aws' --exclude='.cache' --exclude='.dbus' --exclude='.fzf' --exclude='.pki' \
  --exclude='.config/zsh' --exclude='.config/fish' \
  "$source_dir"/.??* "$target_dir"
