#!/bin/bash

# Limit to as2-streaming-user
if [ ! "$HOME" = "/home/as2-streaming-user" ]; then
  echo "Home: $HOME"
  exit 1
fi

source_dir="$HOME"
home_folder="$HOME/MyFiles/HomeFolder"
target_dir="$home_folder/_configs"

# Ensure source directory exists
if [ ! -d "$source_dir" ]; then
  echo "Source directory does not exist: $source_dir" >&2
  exit 1
fi

# Ensure target directory exists
if [ ! -d "$home_folder" ]; then
  echo "Home Folder directory does not exist: $home_folder" >&2
  exit 1
else
  mkdir -p "$target_dir"
  owner=$(stat -c '%U' "$target_dir")
  if [ "$owner" = "root" ]; then
    echo "The owner of the target directory is root: $target_dir"
    exit 1
  fi
fi

# [NOTE] saving configs as a tarball because access to the HomeDFolder is SLOW
tar --exclude='.aws' \
    --exclude='.cache' \
    --exclude='.dbus' \
    --exclude='.fzf' \
    --exclude='.pki' \
    --exclude='.config/zsh' \
    --exclude='.config/fish' \
    -cvf - \
    -C "$source_dir" \
    $(find ~/ -name '.*' -print) \
    | zstd > dotfiles.tar.zst

cp -f dotfiles.tar.zst "$target_dir"
